dataset:
  dataset_name: health_fact
  tokenizer_name: bert-base-uncased
  add_metadata_to_input: True
  metadata_params:
    n_most_common_sources: 30
    n_most_common_subjects: 33
  use_sentence_transformer: True
  sentence_transformer_params:
    sentence_transformer_name: multi-qa-MiniLM-L6-cos-v1
    top_k_sentences: 5
  save_path: ../data/dataset_top_k_with_metadata

model:
  pretrained_model_name: bert-base-uncased
  metadata_in_input: True
  subject_layer_params:
    n_inputs: 33
    n_neurons: 128
  source_layer_params:
    n_inputs: 30
    n_neurons: 128
  bert_layer_params:
    n_inputs: 768
    n_neurons: 128
  output_layer_params:
    n_outputs: 4
  save_path: ../bert_top_k_with_metadata

training:
  optimizer_params:
    optimizer: madgrad
    lr: 1e-4
  metadata_in_dataset: True
  batch_size: 32
  n_epochs: 20
  device: cuda